### PR TITLE
shhh!

### PR DESCRIPTION
**Pull request by skyem123**
Made it so that the decorations are enabled for a player if that player
has certain skins.
Also fixed a typo in a warning message.

### CODE REVIEW

**Comment by RX14** [comment]
Ugh, now everyone with my skin gets ears, and they didn't even work for it!

**Comment by Victorious3** [comment]
Yeah, that's what I think too. Its meant to be special, if I ever release a real cosplay mod I'll do it that way.

**Comment by RX14** [comment]
@Victorious3 I like the idea of it being skin based though so I can switch out of cosplay mode, but add in an extra check for usernames. I wonder if it's still the same skin ID when i change back though...

**Comment by skyem123** [comment]
Well, it wouldn't be that hard to make it have an extra check...

**Comment by RX14** [comment]
i would love to be able to toggle it from the client tho

**Comment by skyem123** [comment]
That might be starting to go into "very unnecessary" territory...

**Comment by Victorious3** [comment]
No, you won't be able to toggle it, how would that work? Its client side only.

**Comment by skyem123** [comment]
One problem, I cannot test the UUID checking on my own.

**Comment by skyem123** [comment]
Alright, should be done.

**Comment by skyem123** [comment]
"\<Sava\> Vic told me that I can be cirno[...]"

**Comment by skyem123** [comment]
@Victorious3! You seem to have forgotten the nano key image...

**Comment by skyem123** [comment]
Also the "cirno" mode doesn't work in first person mode.
Also, it seems to be (maybe) broken for me...

**Pull request merged**
