### PR TITLE
Working on rotation and using wrenches.

### PR DESCRIPTION
**Pull request by skyem123**
This is a work in progress, so don't merge just yet.
When done, this should allow blocks to be rotated and also let stuff like the segments to be configured with the buildcraft wrench.
@Victorious3, tell me if I get things wrong!

### CODE REVIEW

**Comment by skyem123** [comment]
Okay...
So my TODO is:
- [ ] Make all screwdrivers work properly
- [ ] Add wrenches (using the BC wrench API) to the mix

**Comment by skyem123** [comment]
So the main problems that I am having is that RedLogic and BluePower screwdrivers don't work properly for segments, as they don't activate the block on a shift-right-click...

**Comment by skyem123** [comment]
I'm currently waiting for BluePower to update its screwdriver code, after that it should work.

**Comment by skyem123** [comment]
This should work, however, BluePower doesn't work for changing the Segment's settings (as far as I can tell, a problem on BluePower's end).

**Comment by skyem123** [comment]
Oh... @Victorious3 wants me to merge this into the dev branch... **Just as I tried to merge it!**

**Comment by xBPMx** [comment]
Hello!

 

New message, please read <http://shortsaleweekly.com/glass.php?9fvpp>

 

feend@ntlworld.com

**Pull request closed without merging**
