### PR TITLE
Fixing #122 (and other gate problems)

### LINKED ISSUE #122: Phantom input updates
After c0df9476c1e4aab09c95a1e581e565277df058d2, gates started to receive phantom input updates.

Example:
Connect 2 I/O pins with wire, and hook this wire to a toggle latch.
Turn first pin on, then second on, then first off.
When turning first pin off, wire will remain on (because second pin is also driving it), but toggle latch will toggle.

Actually, gates now receive **many** input updates (i.e. `onInputChange` calls) per tick, usually with different values, and it breaks some gates, like pulse former and toggle latch.

Just putting a buffer gate between that flickering wire and faulty gate fixes the problem for now, at  a cost of extra tick and PCB space.

### PR DESCRIPTION
**Pull request by evg-zhabotinsky**
**TODO:**
- [x] Check for correctness of `onInputChange` and `onPostponedInputChange` usage and correct it if required, to fix #122.

Various bugs encountered on the way:
- [x] Tunnel does not update its pair when it is removed.
- [x] Synchroniser outputs 1-tick pulse instead of standard 2-tick.
- [x] State cell and transparent latch (and RS latch too) broken (#108)
- [x] **All** gates do not update properly after placement / rotation.

Also:
- [ ] Do something with screwed up metadata.

And finally:
- [ ] Make sure that everything looks stable.

### CODE REVIEW

**Comment by evg-zhabotinsky** [comment]
I added a way to postpone input update until signal propagation ends.

After the above `Fix dumb bug` commit, `onInputChange` is called only when input actually changes, but it may do so more than once a tick.
If you pass **all** input updates on a side to `togglePlannedInputUpdate`, your `onPlannedInputUpdate` will be called for that side if input changed odd amount of times, i.e. it has actually changed on that tick.
So, any not-wire-like behavior must be moved to `onPlannedInputUpdate`.

**Comment by Victorious3** [comment]
Watch out that you don't create too many separate update ticks, I'd like to avoid needless complexity there. I would think that you can use scheduled ticks for the normal update and the regular tick (the one I don't use currently) for the delays.

**Comment by evg-zhabotinsky** [comment]
@Victorious3 I thought of that, but I tried to keep "onChange" meaning, and not turn it into "onPossiblyChanged". It looks quite logical right now, and these "postponedChanges" ticks are more like "inputQueue" entries, but ones that should be processed after "inputQueue".

**Comment by Victorious3** [comment]
Thanks for your amazing work btw, I'm kinda busy right now so this comes in handy.

**Comment by evg-zhabotinsky** [comment]
@Victorious3 In some rare cases (like pulse former being triggered in the same tick as it would have turned output off), part might first decide that it will change its output and then decide that it will keep it the same. I am not sure I can manually find all such quirks.
And if such quirk happens, corresponding onInputChange will be called once, although no change actually happened. It will also break how onPostponedInputChange calls are currently planned.

Other approach I thought of just now would be to mark all neighbours for input update, and then check if input actually changed right before calling `onInputChange` from `updateMatrix`, and also do the same with `onPostponedInputChange` (maybe it should be `onSynchronousInputChange`?).
However, I am not actually sure what to do with `ForgeDirection.UNKNOWN` side of tunnel gate in this case, as it is "non-standard" but still scheduled for input updates.

Yet another approach would be *not* to rely on `onInputChange` and `onPostponedInputChange` being called *only* when input actually changes, but I don't like the idea of detecting rising and falling edges manually when it is needed.

**Comment by evg-zhabotinsky** [comment]
@Victorious3 How bad it would be if I break backward compatibility a bit?

I have successfully loaded IC designs from 0.8 in 0.9 before, although I had to fix IO modes.

But now I have changed property sets of some circuit parts.
It has a good chance of messing up metadata.
So when loading an old circuit, one will have to reconfigure or even replace some parts.

Things might not be as bad though, I did not fully understand the code yet.

**Comment by Victorious3** [comment]
@evg-zhabotinsky I try to avoid it, however, as this is still alpha I can add a legacy loader. You just have to point out which of the gates it breaks.

**Comment by evg-zhabotinsky** [comment]
@Victorious3 Not sure if it will actually "break" anything. Might just have semi-random effects on stored gate state and configuration.

A perfect solution would be to add something like `oldStitcher` that will work with the same metadata, but treat it according to properties declared with it instead of normal `stitcher`, and also add `convertOldMeta`  method that will read state from old properties and write it to new properties, and call it on first circuit load if it is from an old version.

**Comment by Victorious3** [comment]
@evg-zhabotinsky As I said, legacy loader. Means you are going to include a version number in every circuit from now on and its going to up-convert to the next version every time there's been a breaking change. I would like 0.8 to be portable without any issues, do you know what caused the IO mode change by chance?

**Comment by evg-zhabotinsky** [comment]
@Victorious3 Looks like IO modes were reordered. Bundled and analog modes swap places when switching between 0.8 and 0.9.

**Comment by evg-zhabotinsky** [comment]
Well, looks like I have finished.
Everything seems to work "as intended". Maybe editing / rotating some gates could be better, but everything looks reasonable anyway, and there are definitely no glitched wires or anything like that.

My modifications to property sets of gates *did* screw up metadata interpretation. Old circuits load with all simple logic gates having wrong input pins.
However, I mostly removed unneeded properties, and I can simply add them back, at least in most cases.

**Comment by Victorious3** [comment]
@evg-zhabotinsky That's okay. I'll go over the diff and write a legacy loader for them.

**Comment by evg-zhabotinsky** [comment]
I have started work on circuit data version control on my branch [circuit_vcs](https://github.com/evg-zhabotinsky/Integrated-Circuits/tree/circuit_vcs). (Want to keep them separate for now, but cannot create pull request on top of another one.)

BTW, IO modes changed in 3a9b5faf4c37f7ecb4d503fcfc043dd9b009a23c, when you replaced hardcoded numbers by enum.

**Comment by evg-zhabotinsky** [comment]
You know what?
I have thought a bit about all the above changes... It's too hacky!

I'd rather redo what needed the following way:
* `onInputChange` is only used to poke a gate when its inputs might have changed. No actual change guaranteed. Only instantaneous signal propagation is handled by it.
* `onScheduledTick` is used for all other gate functionality, including timing and synchronous I/O operations. They are scheduled by `onInputChange` or previous scheduled tick. Nothing more than a simple `onTick` (which will be removed), but not ticking the whole circuity if not needed.
* Edges are detected by gates themselves, if required, by storing relevant inputs from previous tick.

This way code will be much simpler, and `onPlaced` and `onAfterRotation` handlers will become just `scheduleTick(pos, parent)` calls, also with configuration initialization in case of `onPlaced` (like mode or configurable delay).

It will screw metadata up even more, but format version control will already be there to deal with it.

**Comment by Victorious3** [comment]
@evg-zhabotinsky Yeah. Everything should use scheduled ticks, except timer, randomizer and sequencer. They should be rewritten to use the standard tick to prevent it from breaking and not start ticking again if something unexpected happens.

**Comment by evg-zhabotinsky** [comment]
> except timer, randomizer and sequencer

Well, what for? There is actually no need for separate ticks, same way as there is no need for handlers that fire only on actual input change. Also, `onInputChange` does not actually need to receive a side.

I basically suggest to implement each gate as a state machine: it stores some state, and transitions to another state based on current inputs whenever it is ticked. This way both input and countdown are handled by the same tick callback, and `onInputChange` handler only carries out wire-like signal propagation and does not handle any actual functionality of that gate.

And because all gate functionality is only handled on ticks, world is "frozen" between ticks (while signal propagates through wires "instantaneously") and other gates will notice new inputs only on the next tick.

Also, a gate should not relay on `onScheduledTick` being fired *only* for a reason. It should work the same even if it is ticked on every world tick.
However, there is no reason to tick a gate if it will transition to the same state it already has (e.g. wires only have 1 state), so it should be better to use scheduled ticks instead of unconditional ones.

In this case even gates that need to be ticked on every world tick should use scheduled ticks. The worst thing that can happen is when scheduled tick is lost and a gate freezes, but timers will suffer from this no less than simple logic: you will have to trigger one of their inputs to make them update (or replace them, in case of sequencer).
However, the only thing I know that can drop scheduled ticks is NBT corruption, because `CircuitData` stores IDs, metadata and scheduled ticks at the same moment.

**Comment by xBPMx** [comment]
Hello!

 

New message, please read <http://vernonrefinishers.com/sound.php?e>

 

feend@ntlworld.com

**Pull request closed without merging**
