### PR TITLE
Config UI

### PR DESCRIPTION
**Pull request by Achati**
added the ingame config ui and a config option for 7segment displays

### CODE REVIEW

**Comment by skyem123** [comment]
O_o
Okay, I want @Victorious3 to have a look at this, and after that, I'll teach you how to squash git commits.

**Comment by Achati** [comment]
you are a meanie

**Comment by skyem123** [comment]
@Victorious3 is teaching me well...
Sadly, Vic has yet to teach me enough Java yet...

**Comment by Victorious3** [comment]
I'll pull it once you squashed some of those commits...

**Pull request merged**
