### PR TITLE
Made it so that the soldering iron is not needed in creative mode to place circuits

### PR DESCRIPTION
**Pull request by skyem123**
I'm doing this in a pull request so @Victorious3 can reject this if they want to.

### CODE REVIEW

**Comment by evg-zhabotinsky** [comment]
A similar suggestion: allow to use floppies instead of ICs in creative. It should be mostly copy-paste as I understand it.

**Comment by skyem123** [comment]
That sounds good, should I try to implement it, or should we wait for Vic's suggestion?

**Comment by Victorious3** [comment]
Yeah, both sound good. For that a relocation / rewrite of the storage methods into a better location is needed, since a lot of the code is scattered around the place right now.

**Comment by skyem123** [comment]
Should I try to work on that, or should @Victorious3 / @evg-zhabotinsky work on it?

**Pull request merged**
