### PR TITLE
Hopefully fixed #120

### LINKED ISSUE #120: Gates do not update their neighbours on disconnect
Basically, that's all that remains from #109 (not limited yo NOT gate of course):
>Different example of weirdness:
>screenshot from 2015-06-10 12 10 36screenshot from 2015-06-10 12 10 49
>screenshot from 2015-06-10 12 15 06screenshot from 2015-06-10 12 19 17
>So, you just change pin configuration of some gate and end up with glitched wire.
>Especially annoying in huge complex circuits.

How it actually happens:
* Gate has active output to its neighbor.
* That active output is disconnected (by rotating / changing mode)
* The neighbor is not updated because it is no longer connected
* The neighbor is stuck with phantom signal from edited gate until other update hits it.

I have a fix, but I am not completely sure I did not break anything on the way.
Everything looks fine so far.

### PR DESCRIPTION
**Pull request by evg-zhabotinsky**
Fixed parts not updating their neighbours after disconnecting from them.
Made code a bit more readable and reduced copy-paste usage.

Everything works fine so far, but I am not completely sure.

I added 2 `public final` methods to `CircuitPart`:
* `getCachedInputFromSide` gets input values that gate stores in its property. Used in `getInputFromSide`. Also used to check if neighbour should actually be updated in `notifyNeighbours`, instead of `getInputFromSide` (this fixes #120).
* `hasConnectionOnSide` checks if part is actually connected to anything on specified side. Used in various places to increase code readability.

Also, `PartNull` no longer `canConnect` on any side, and uses standard `onPlaced` handler (it should work properly now).

### CODE REVIEW

**Comment by evg-zhabotinsky** [comment]
Oops infinite loop. Looks like it's not ready yet.

**Comment by evg-zhabotinsky** [comment]
Now my monstrous single-chip 2-door lock with up to 6 digit key is working properly, as before :-)

**Comment by Victorious3** [comment]
Looks good, thanks~

**Comment by Victorious3** [comment]
@evg-zhabotinsky Btw, please stay on `dev`

**Pull request merged**
