### PR TITLE
Fix all gate glitches

### LINKED ISSUE #122: Phantom input updates
After c0df9476c1e4aab09c95a1e581e565277df058d2, gates started to receive phantom input updates.

Example:
Connect 2 I/O pins with wire, and hook this wire to a toggle latch.
Turn first pin on, then second on, then first off.
When turning first pin off, wire will remain on (because second pin is also driving it), but toggle latch will toggle.

Actually, gates now receive **many** input updates (i.e. `onInputChange` calls) per tick, usually with different values, and it breaks some gates, like pulse former and toggle latch.

Just putting a buffer gate between that flickering wire and faulty gate fixes the problem for now, at  a cost of extra tick and PCB space.

### PR DESCRIPTION
**Pull request by evg-zhabotinsky**
A second attempt (#123 was the first one).
Added less code, deleted more :-)
Simplified some things and generally made everything less error-prone.

Fixed #122 and #108.

**How it works now:**
* Gate logic is performed on ticks, signal propagation is done between ticks.
* `onScheduledTick` is the only tick handler. It can be safely called on every world tick, but to reduce load it is only called when previously scheduled.
* `onInputChange` handles instantaneous signal propagation *and nothing else*. It is called after being scheduled by `scheduleInputChange` call. These methods no longer receive side as an argument. It also calls `scheduleTick` whenever performing gate logic might be required.
* `onInputChange` and `onScheduledTick` callbacks do not guarantee that anything actually happened. They are only notifications that something *might* has changed, although they should not fire without reason too often.
* (**Edit**) When circuit is edited, signals are propagated *immediately* through wires, even if that circuit is not ticking at the moment (i.e. paused, in stepped execution mode), but affected gates are *not* ticked. Gates are only ever ticked together with the whole circuit.

I have tested all gates one by one, but there might still be minor bugs like forgetting to call `markForUpdate` that do not affect anything in an obviously incorrect way.

Also, as in #123, **gate metadata is incompatible with 0.8 or previous 0.9 versions**. It is more or less inevitable, and non-trivial conversion is required in some cases.
*Waiting for circuit format version control system.*

### CODE REVIEW

**Comment by evg-zhabotinsky** [comment]
*Stepped circuit simulation seems to work perfectly!*

I have added a simple check like `if gate at (1,1) is rotatable and rotated as before, return immediately` to the beginning of `updateMatrix` method to test it.
All the edits happen immediately (including toggle latch and IO pin toggle), together with signal propagation through wires (including cells and tunnels).
After disabling any of multiple signal sources that currently drive a single wire, that wire stays turned on as it should.
Gates only update their state on ticks, e.g. a wire connecting inverter's output to its input will switch on on one tick, then off on the next tick, then on again and so on.

The only thing that remains for it to really work is a proper way to control stepping from GUI.

---

*Off-topic:* Tunnel and RS latch are the two gates with the hackiest implemented in this mod!
Tunnel is hacky because it has to check its old / new pair on many occasions.
RS latch is hacky because when it is in "special" mode, current wire system requires it to act as an instantaneous inverter, which can easily cause infinite loops in signal propagation if done incorrectly!

**Comment by evg-zhabotinsky** [comment]
@Victorious3 *How __exactly__ is one supposed to convert gates from old version to new?* I don't quite get it from your code.

Please explain how would you do it in case of RS latch (because it has suffered all possible attribute changes):
* Old properties (with offsets):
  * 0: INPUT, 4 bits (15 max)
  * 4: ROTATION, 2 bits (3 max)
  * 6: OUT, bit
  * 7: TMP, bit
  * 8: MODE, 2 bits (3 max)

* New properties:
  * 0: INPUT, 4 bits (15 max)
  * 4: ROTATION, 2 bits (3 max)
  * 6: STATE, 2 bits (2 max)
  * 8: CHECK, bit
  * 9: MODE, 2 bits (3 max)

* Conversion algorithm (slightly pseudocode):

    ```
    new.INPUT = old.INPUT; new.ROTATION = old.ROTATION;
    new.MODE = old.MODE; // New offset is different from old in this case
    new.CHECK = false;
    new.STATE = old.OUT ? 1 : 2;
    scheduleInputChange();
    notifyNeighbours();
    ```

* Also, need to call `propagateSignals()` after the whole circuit is processed like above.

* Note that property OUT is not present in new version, and TMP is not used at all.

**Comment by Victorious3** [comment]
@evg-zhabotinsky I can't expose the properties there as they might as well change between versions so their offset wouldn't be consistent. What mine allows you to do is to copy parts of the metadata. (I'll add something for changing it directly)
```
PartTransformer transformer = new PartTransformer() {{
    old.allocate(0, 6); // First two properties didn't change, they make up 6 bits
    old.skip(2);
    old.allocate(1, 2); // Last property

    transformed.allocate(0, 6);
    transformed.skip(3);
    transformed.allocate(1, 2);
}};
```
This doesn't include the two new properties.

**Comment by Victorious3** [comment]
@evg-zhabotinsky Now it would be:

```java
PartTransformer transformer = new PartTransformer() {{
        old.allocate(0, 6); // First two properties didn't change, they make up 6 bits
        old.allocate(1);
        old.skip(1);
        old.allocate(2, 2); // Last property

        transformed.allocate(0, 6);
        transformed.allocate(3, 2); // STATE
        transformed.allocate(4); // CHECK
        transformed.allocate(2, 2);
    }

    @Override
    protected void transformImpl() {
        setInt(3, getBit(1) ? 1 : 2);
    }

    @Override
    public void postTransform(Vec2 crd, CircuitData cdata) {
        cdata.scheduleInputChange(crd);
        cdata.markForUpdate(crd);
        cdata.getPart(crd).onInputChange(crd, cdata.getCircuit());
    }
};
```

**Comment by evg-zhabotinsky** [comment]
Hmmm
I started writing a converter, but:

What will happen if e.g. `scheduleInputChange` will be removed in a future version?
What if `CircuitData` changes too much?

I suspect the only real future-proof solution is to have a stripped down self-sufficient version of `CircuitData` read circuit from NBT, convert it and then write it back to NBT for the next version to read.

I think it is reasonable to have subpackages like `Version_0_8` and `Version_0_9` inside `Legacy` that will have all required classes copied to them, and only allow using their own and older legacy classes within them. It can be a *lot* of duplicated code though.

I have also seen an alternative solution (in GregTech if I remember right): have every mod version either perform conversion from a previous version or perform no conversion at all, and explicitly state that you have to install intermediate versions and visit all your chunks with each of them when you upgrade. It is simpler, but not as foolproof.

**Comment by Victorious3** [comment]
@evg-zhabotinsky Not planning to change them all that often.
For the sockets I'd need dummy TEs but I decided that the circuits themselves are more important. After all this is still alpha and I don't want to write a whole bunch of legacy code *before* releasing 1.0.

**Comment by evg-zhabotinsky** [comment]
I am still there! Just was a bit busy sitting my exams and moving out of dorms.

I have already written some converters.
I changed property allocator a bit to allow extending converters (a-la `cp/part` hierarchy). Now it resembles `PropertyStitcher` a bit more.

**Pull request merged**
